#!/usr/bin/env python3
"""Local token gate in front of the dashboard's ttyd instances.

Background: ttyd (started by scripts/ttyd-shells.sh) used to listen writable
on 127.0.0.1:768x with no origin check and no credential, so any page open
in the same browser could open a WebSocket to it and run commands on the
host (PlanDeTestSecurite-ShellBridge.txt, item 0.1). WebSockets are not
subject to CORS, so `ttyd --check-origin` cannot fix it without also
breaking the dashboard's own cross-port connections.

This proxy is the root fix (PlanCorrectif-ShellBridge-0.1.txt, option 1).
ttyd now listens on a per-slot UNIX socket -- unreachable from the browser.
This process listens on 127.0.0.1:768x in its place and forwards to that
socket ONLY when the request carries `?session=<token>` (the token
generated by `ttyd-shells.sh start`). Anything else gets 403. The check is
constant-time.

The dashboard adds ?session to the terminal iframe src and to every direct
WebSocket URL it opens. ttyd's OWN bundled client (loaded inside that
iframe) does not know the token, so when the proxy serves ttyd's HTML page
it injects a small shim at the top (inject_session_script) that makes the
client's `fetch('/token')` and `new WebSocket('/ws')` carry ?session too. A
cookie was tried instead but a SameSite cookie cannot ride a request from
an iframe whose top-level page is the dashboard (file:// or another port),
and Chrome blocks it as third-party.

After the head is validated (?session stripped, any client credential
header dropped), the connection is an opaque byte pipe -- except the ttyd
HTML response, whose body is buffered and patched. ttyd itself runs with
no credential (`-c`): its UNIX socket lives under $XDG_RUNTIME_DIR (0700),
already reachable by this user only, and a `-c` value would just leak on
ttyd's command line (Sweep3 §7.2a). The proxy's ?session token is the sole
gate on the browser side.

Loopback only, no TLS. Usage:

  shell-proxy.py --token-file <path> --route 7681=<sock> [--route 7691=<sock> ...]
"""

import argparse
import asyncio
import hmac
import sys
from urllib.parse import urlsplit, urlunsplit, parse_qsl, urlencode

HEAD_LIMIT = 64 * 1024
PIPE_CHUNK = 64 * 1024


def log(msg):
    sys.stderr.write("[shell-proxy] " + msg + "\n")
    sys.stderr.flush()


async def read_head(reader):
    """Read bytes up to and including the CRLFCRLF that ends an HTTP head.

    Returns (head_bytes, leftover_bytes) or (None, b'') if the peer closed
    or sent more than HEAD_LIMIT without terminating the head.
    """
    buf = b""
    while b"\r\n\r\n" not in buf:
        if len(buf) > HEAD_LIMIT:
            return None, b""
        chunk = await reader.read(PIPE_CHUNK)
        if not chunk:
            return None, b""
        buf += chunk
    head, leftover = buf.split(b"\r\n\r\n", 1)
    return head + b"\r\n\r\n", leftover


def parse_head(head_bytes):
    text = head_bytes.decode("latin-1")
    lines = text.split("\r\n")
    request_line = lines[0]
    parts = request_line.split(" ")
    if len(parts) != 3:
        return None
    method, target, version = parts
    headers = []
    for line in lines[1:]:
        if not line:
            continue
        if ":" not in line:
            return None
        name, value = line.split(":", 1)
        headers.append((name.strip(), value.strip()))
    return {"method": method, "target": target, "version": version,
            "headers": headers}


def header_get(headers, name):
    low = name.lower()
    for n, v in headers:
        if n.lower() == low:
            return v
    return None


def token_ok(candidate, token):
    return bool(candidate) and hmac.compare_digest(candidate, token)


def authorized(parsed, token):
    """A request is let through iff it carries ?session=<token>.

    The dashboard adds it to the terminal iframe src and to every direct
    WebSocket URL; the shim injected into ttyd's own page (see
    inject_session_script) adds it to ttyd's client fetch('/token') and
    new WebSocket('/ws'). So nothing legitimate reaches ttyd without it,
    and there is no cookie / Origin fallback to reason about.
    """
    split = urlsplit(parsed["target"])
    for k, v in parse_qsl(split.query, keep_blank_values=True):
        if k == "session":
            return token_ok(v, token)
    return False


def strip_session(target):
    split = urlsplit(target)
    kept = [(k, v) for k, v in parse_qsl(split.query, keep_blank_values=True)
            if k != "session"]
    return urlunsplit((split.scheme, split.netloc, split.path,
                       urlencode(kept), split.fragment))


def rewrite_head(parsed, token, ws):
    target = strip_session(parsed["target"])
    out = ["%s %s %s" % (parsed["method"], target, parsed["version"])]
    # Strip any client-supplied credential header -- ttyd runs with no
    # `-c` (the UNIX socket is already user-private, Sweep3 §7.2a), so the
    # proxy forwards nothing of its own; these are just belt-and-braces.
    drop = {"authorization", "x-shell-session"}
    if not ws:
        # One upstream request per connection: the proxy validates and
        # rewrites a *head*, it does not re-parse follow-up requests
        # pipelined on a kept-alive socket. Forcing close makes the
        # browser open a fresh (individually handled) connection per
        # asset. Harmless on loopback. Also drop Accept-Encoding so ttyd
        # sends the index page uncompressed and inject_session_script can
        # patch it. WS upgrades keep their headers untouched.
        drop |= {"connection", "keep-alive", "proxy-connection",
                 "accept-encoding"}
    for name, value in parsed["headers"]:
        if name.lower() in drop:
            continue
        out.append("%s: %s" % (name, value))
    if not ws:
        out.append("Connection: close")
    return ("\r\n".join(out) + "\r\n\r\n").encode("latin-1")


def is_ws_upgrade(parsed):
    up = header_get(parsed["headers"], "upgrade")
    if up and up.lower() == "websocket":
        return True
    return urlsplit(parsed["target"]).path.rstrip("/") == "/ws"


# Patched into the top of ttyd's own served page so its bundled client
# reaches /token and /ws with the session token -- the client is same-origin
# with ttyd (127.0.0.1:768x) but its top-level page is the dashboard
# (file:// or 127.0.0.1:<other-port>), so no SameSite cookie survives to
# carry auth for it. The token only ever lives in ttyd's own origin here,
# which already hosts the terminal; another origin cannot read it.
_SHIM = (
    "<script>(function(){var T=%s;"
    "function tag(u){if(typeof u!=='string')return u;"
    "if(u.indexOf('session=')>-1)return u;"
    "var p=u.split('#')[0].split('?')[0];"
    "if(p.slice(-3)!=='/ws'&&p.slice(-6)!=='/token')return u;"
    "return u+(u.indexOf('?')<0?'?':'&')+'session='+T;}"
    "var _f=window.fetch;if(_f)window.fetch=function(u,o){"
    "return _f.call(this,(u&&u.url)?new Request(tag(u.url),u):tag(u),o);};"
    "var _W=window.WebSocket;if(_W){var P=window.WebSocket=function(u,pr){"
    "return arguments.length>1?new _W(tag(u),pr):new _W(tag(u));};"
    "P.prototype=_W.prototype;P.CONNECTING=0;P.OPEN=1;P.CLOSING=2;P.CLOSED=3;}"
    "var _o=XMLHttpRequest.prototype.open;"
    "XMLHttpRequest.prototype.open=function(m,u){"
    "arguments[1]=tag(u);return _o.apply(this,arguments);};"
    "})();</script>"
)


def inject_session_script(body, token):
    shim = (_SHIM % ('"' + token + '"')).encode("latin-1")
    for anchor in (b"<head>", b"<head ", b"<html>", b"<html "):
        i = body.find(anchor)
        if i != -1:
            j = body.find(b">", i) + 1
            return body[:j] + shim + body[j:]
    return shim + body


def resp_header_get(head_bytes, name):
    low = name.lower()
    for line in head_bytes.decode("latin-1").split("\r\n")[1:]:
        if ":" in line:
            n, v = line.split(":", 1)
            if n.strip().lower() == low:
                return v.strip()
    return None


def rebuild_resp_head(head_bytes, new_len):
    lines = head_bytes.decode("latin-1").split("\r\n")
    out = [lines[0]]
    seen_cl = False
    for line in lines[1:]:
        if not line:
            continue
        n = line.split(":", 1)[0].strip().lower()
        if n == "content-length":
            out.append("Content-Length: %d" % new_len)
            seen_cl = True
        elif n in ("content-encoding", "transfer-encoding"):
            continue
        else:
            out.append(line)
    if not seen_cl:
        out.append("Content-Length: %d" % new_len)
    out.append("Connection: close")
    return ("\r\n".join(out) + "\r\n\r\n").encode("latin-1")


async def read_all(reader, initial):
    chunks = [initial] if initial else []
    while True:
        c = await reader.read(PIPE_CHUNK)
        if not c:
            break
        chunks.append(c)
    return b"".join(chunks)


async def pipe(reader, writer):
    try:
        while True:
            chunk = await reader.read(PIPE_CHUNK)
            if not chunk:
                break
            writer.write(chunk)
            await writer.drain()
    except (ConnectionError, asyncio.CancelledError):
        pass
    finally:
        try:
            writer.write_eof()
        except (OSError, RuntimeError):
            pass


async def deny(writer):
    writer.write(b"HTTP/1.1 403 Forbidden\r\nContent-Length: 0\r\n"
                 b"Connection: close\r\n\r\n")
    try:
        await writer.drain()
    except ConnectionError:
        pass
    writer.close()


async def handle_client(reader, writer, sock_path, token):
    peer = writer.get_extra_info("peername")
    try:
        head_bytes, leftover = await read_head(reader)
        if head_bytes is None:
            writer.close()
            return
        parsed = parse_head(head_bytes)
        if parsed is None:
            await deny(writer)
            return
        if not authorized(parsed, token):
            log("403 %s %s from %s" % (parsed["method"],
                                       parsed["target"].split("?")[0], peer))
            await deny(writer)
            return

        try:
            up_reader, up_writer = await asyncio.open_unix_connection(sock_path)
        except (OSError, ConnectionError) as exc:
            log("upstream %s unavailable: %s" % (sock_path, exc))
            writer.write(b"HTTP/1.1 502 Bad Gateway\r\nContent-Length: 0\r\n"
                         b"Connection: close\r\n\r\n")
            await writer.drain()
            writer.close()
            return

        ws = is_ws_upgrade(parsed)
        up_writer.write(rewrite_head(parsed, token, ws))
        if leftover:
            up_writer.write(leftover)
        await up_writer.drain()

        if not ws:
            resp_head, resp_leftover = await read_head(up_reader)
            if resp_head is None:
                writer.close()
                return
            ctype = (resp_header_get(resp_head, "content-type") or "").lower()
            if parsed["method"] == "GET" and ctype.startswith("text/html"):
                # ttyd's terminal page -- patch it so its own client speaks
                # ?session, then hand the whole (re-sized) response over.
                body = inject_session_script(
                    await read_all(up_reader, resp_leftover), token)
                writer.write(rebuild_resp_head(resp_head, len(body)))
                writer.write(body)
                await writer.drain()
                writer.close()
                return
            writer.write(resp_head)
            if resp_leftover:
                writer.write(resp_leftover)
            await writer.drain()

        t1 = asyncio.ensure_future(pipe(up_reader, writer))
        t2 = asyncio.ensure_future(pipe(reader, up_writer))
        done, pending = await asyncio.wait(
            {t1, t2}, return_when=asyncio.FIRST_COMPLETED)
        for t in pending:
            t.cancel()
    except (ConnectionError, asyncio.CancelledError):
        pass
    finally:
        writer.close()


async def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--token-file", required=True,
                    help="file holding the session token (not passed on argv)")
    ap.add_argument("--route", action="append", default=[], metavar="PORT=SOCK",
                    help="listen on 127.0.0.1:PORT, forward to UNIX socket SOCK")
    args = ap.parse_args()

    try:
        with open(args.token_file, "r") as fh:
            token = fh.read().strip()
    except OSError as exc:
        log("cannot read token file: %s" % exc)
        return 1
    if not token:
        log("token file is empty -- refusing to start")
        return 1

    routes = []
    for spec in args.route:
        if "=" not in spec:
            log("bad --route %r (want PORT=SOCK)" % spec)
            return 1
        port_s, sock = spec.split("=", 1)
        routes.append((int(port_s), sock))
    if not routes:
        log("no --route given")
        return 1

    servers = []
    for port, sock in routes:
        srv = await asyncio.start_server(
            lambda r, w, s=sock, t=token: handle_client(r, w, s, t),
            host="127.0.0.1", port=port)
        servers.append(srv)
    log("listening on %s" % ", ".join("127.0.0.1:%d" % p for p, _ in routes))

    try:
        await asyncio.gather(*(s.serve_forever() for s in servers))
    finally:
        for s in servers:
            s.close()
    return 0


if __name__ == "__main__":
    try:
        sys.exit(asyncio.run(main()))
    except KeyboardInterrupt:
        pass
